name: Nicolai
favicon: null
layout_spectrum: 0.24441
typography_spectrum: 0.25939
title: street photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4c4c4c'
    - '#6c6c6c'
    - '#ececec'
    - '#adadad'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
